name: Merge CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn
        
      - name: Lint files
        run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn
        
      - name: Run prettier
        run: yarn prettier
        
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn
        
      - name: Run tests
        run: yarn test